# Generated by Django 5.2.9 on 2026-01-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], max_length=10)),
                ('requiere_validacion_profesor', models.BooleanField(default=False)),
                ('completada_por_alumno', models.BooleanField(default=False)),
                ('validada_por_profesor', models.BooleanField(default=False)),
                ('colaboradores', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'ALUMNO'}, related_name='tareas_colabora', to='usuarios.usuario')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='usuarios.usuario')),
                ('profesor_validador', models.ForeignKey(blank=True, limit_choices_to={'rol': 'PROFESOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_a_validar', to='usuarios.usuario')),
            ],
        ),
    ]
