# Generated by Django 5.2.9 on 2026-01-07 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('rol', models.CharField(choices=[('ALUMNO', 'Alumno'), ('PROFESOR', 'Profesor')], max_length=10)),
            ],
        ),
    ]
